name: Go1.16

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    name: Test Go1.16 for macOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Go Test
      run: GOARCH=amd64 go test -v .

  linux:
    name: Test Go1.16 for Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Go Test amd64
      run: GOARCH=amd64 go test -v .

    - name: Go Test 386
      run: GOARCH=386 go test -v .

  windows:
    name: Test Go1.16 for Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Go Test amd64
      run: |
        set GOARCH=amd64
        go test -v .

    - name: Go Test 386
      run: |
        set GOARCH=386 
        go test -v .
