name: Go1.23

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    name: Test Go1.23 for macOS
    runs-on: macos-13
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -ldflags="-checklinkname=0" -v .

    - name: Install igop
      run: (cd ./igop && go install -ldflags="-checklinkname=0" -v)

    - name: Go Test
      run: GOARCH=amd64 go test -ldflags="-checklinkname=0" -race -v .

    - name: Test $GOROOT/test
      run: GOARCH=amd64 go run ./cmd/igoptest

  linux:
    name: Test Go1.23 for Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -ldflags="-checklinkname=0" -v .

    - name: Install igop
      run: (cd ./igop && go install -ldflags="-checklinkname=0" -v)

    - name: Go Test amd64
      run: GOARCH=amd64 go test -ldflags="-checklinkname=0" -race -v .

    - name: Test $GOROOT/test
      run: GOARCH=amd64 go run ./cmd/igoptest

  windows:
    name: Test Go1.23 for Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -ldflags="-checklinkname=0" -v .

    - name: Install igop
      run: (cd ./igop && go install -ldflags="-checklinkname=0" -v)

    - name: Go Test amd64
      run: |
        set GOARCH=amd64
        go test -ldflags="-checklinkname=0" -v .

    - name: Test $GOROOT/test amd64
      run: |
        set GOARCH=amd64 
        go run ./cmd/igoptest

    - name: Go Test 386
      run: |
        set GOARCH=386 
        go test -ldflags="-checklinkname=0" -v .

    - name: Go $GOROOT/test 386
      run: |
        set GOARCH=386 
        go run ./cmd/igoptest
